### ISSUE TITLE
tut 6: Add Exception for invalid path

### ISSUE THREAD

**Issue by rohanrajpal** [rohanrajpal/advanced-programming-tutorials#1]
Currently, the code throws out NoProductException if an invalid path is specified when deleting a product.

https://github.com/rohanrajpal/advanced-programming-tutorials/blob/main/tut-6/Database.java#L53

Create a new exception to do the same.

**Comment by CuriousMonkey7** [comment]
Hey, 
I like to contribute in this issue. Please assign to me.
