### ISSUE TITLE
tut 5 is not running.

### ISSUE THREAD

**Issue by vasudevsinghal** [rohanrajpal/advanced-programming-tutorials#11]
When I try to run Main.java in tut5 . I am getting many errors.
`Main.java:77: error: 'else' without 'if'
            else{
            ^
Main.java:86: error: class, interface, or enum expected
    private static int takeIntInput() {
                   ^
Main.java:89: error: class, interface, or enum expected
            try {
            ^
Main.java:91: error: class, interface, or enum expected
            } catch (Exception ne) {
            ^
Main.java:93: error: class, interface, or enum expected
            }
            ^
5 errors
`

**Comment by vasudevsinghal** [comment]
There is extra closing bracket due to which we are getting below 4 errors.

**Comment by rohanrajpal** [comment]
@vasu19126 Can you make a PR to fix the same?
