### ISSUE TITLE
tut-6 inputs are not taking properly

### ISSUE THREAD

**Issue by vasudevsinghal** [rohanrajpal/advanced-programming-tutorials#14]
When i run tut-6 it is really difficult to understand what to enter because it is not printing what we have to enter. Also sometimes we need to enter 2 and 3 inputs together so it is really confusing what we have to enter.

**Comment by rohanrajpal** [comment]
Hmm, what solution do you suggest to this issue?

**Comment by vasudevsinghal** [comment]
I think we just need to add proper print statements to tell user what exactly we need as input

**Comment by rohanrajpal** [comment]
> I think we just need to add proper print statements to tell user what exactly we need as input

alright, take this issue up, I'll assign you right away

**Comment by vasudevsinghal** [comment]
Okay

**Comment by rohanrajpal** [comment]
@vasu19126 Good going. From next time onwards in your PR please mention the issue by using a hashtag followed by the issue number you're addressing.

**Comment by vasudevsinghal** [comment]
Thanks. I keep that in mind.
