### ISSUE TITLE
Bug while creating multiple user in tut7

### ISSUE THREAD

**Issue by CuriousMonkey7** [rohanrajpal/advanced-programming-tutorials#16]
When we create multiple user in program it don't ask for username. It is because you used nextInt in tut7/Game.java and tut7/Menu.java, while taking integer input. I think by taking input as string and parsing it using Integer.parseInt() function to int will resolve this.

**Comment by CuriousMonkey7** [comment]
Refer below case :
![Screenshot 2020-10-23 at 21 42 24](https://user-images.githubusercontent.com/70478296/97032328-45bd5d00-157f-11eb-8b1a-f4f8f9743ed9.png)

**Comment by rohanrajpal** [comment]
Good find. Take this issue up.
