### ISSUE TITLE
Hp should not be negative

### ISSUE THREAD

**Issue by vasudevsinghal** [rohanrajpal/advanced-programming-tutorials#19]
While running tut-7 i found a bug that it hero hp can go negative. I think this should not be less than zero as mentioned in tut-7 pdf.

> You choose to attack
> Your Hp: 60/100Monsters Hp :180/200
> Monster attack!
> Your Hp: 35/100Monsters Hp :180/200
> Choose move: 
> 1) Attack
> 2) Defense
> 3)Special Attack
> 3
> Special power activated
> Performing special attack
> Your Hp: 35/100Monsters Hp :180/200
> Monster attack!
> Your Hp: -4/100Monsters Hp :180/200
> You have died start over
> You are at location 10 Choose path: 
> 1) Go to Location 0
> 2) Go to Location 3
> 3) Go to Location 6
>

**Comment by vasudevsinghal** [comment]
i think if we add Math.max(0, var1.getHp() - this.getAttack()) while setting the hp will do our work.

**Comment by rohanrajpal** [comment]
Good catch, take it up
