### ISSUE TITLE
Issue in equality check

### ISSUE THREAD

**Issue by NITIN23329** [rohanrajpal/advanced-programming-tutorials#3]
https://github.com/rohanrajpal/advanced-programming-tutorials/blob/6e4ef713c367fb63785dede3c606327419cc833a/tut-5/SoftToy.java#L22

**Comment by NITIN23329** [comment]
i think super.equals() method should be called in  if block

**Comment by rohanrajpal** [comment]
Yes, good find! Go ahead and make a PR

**Comment by vasudevsinghal** [comment]
i think if we remove override equals function from CandyBar, StatItems and SoftToy. Then also it's works fine. Because it will call Prize equals function everytime automatically.

**Comment by NITIN23329** [comment]
Yes that will also do the job
