### ISSUE TITLE
Tut 5: Can achieve a better time complexity

### ISSUE THREAD

**Issue by dv-rastogi** [rohanrajpal/advanced-programming-tutorials#9]
Hi! ✋ 
In tut5/Main.java while we are checking if a target has been hit or not, we need not iterate over all the previous hits to check, rather keep a HashMap / HashSet for the same in order to achieve a better time complexity!

Referenced from:
https://github.com/rohanrajpal/advanced-programming-tutorials/blob/623b88a37458b8bf83aac36485a881016e6c17e3/tut-5/Main.java#L45-L46

**Comment by dv-rastogi** [comment]
I would like to contribute to the same!
Thanks!

**Comment by rohanrajpal** [comment]
Good catch. You've been assigned, feel free to submit a PR.

**Comment by dv-rastogi** [comment]
#10 I have submitted a PR for the same! 👍
